name: backend-workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Confirm Bun Installation
        run: bun --version
        env:
          PATH: ${{ env.PATH }}

      - name: Install Dependencies
        run: bun install
        env:
          PATH: ${{ env.PATH }}

      - name: Run Tests
        run: bun test
        env:
          PATH: ${{ env.PATH }}